version: "3"

services:
    gitsearch:
        image: gitsearch
        container_name: gitsearch
        restart: always
        volumes:
            - ".:/app"
        deploy:
          resources:
            limits:
              cpus: "4.0"
              memory: 8G
        networks:
          gitsearch_network:
            ipv4_address: 172.32.0.99
        depends_on:
          - db

    db:
      image: mariadb:10.3
      container_name: db
      restart: always
      environment:
        MYSQL_DATABASE: Gitsearch
        MYSQL_ROOT_PASSWORD: changeme
      ports:
        - "3306:3306"
      volumes:
        - "./Gitsearch_DB.sql:/docker-entrypoint-initdb.d/Gitsearch_DB2.sql"
        - "./data:/var/lib/mysql"

      networks:
        gitsearch_network:
          ipv4_address: 172.32.0.97


    phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_ARBITRARY: "1"
        PMA_HOST: "172.32.0.97"
        PMA_PORT: "3306"
        MYSQL_ROOT_PASSWORD: changeme
        UPLOAD_LIMIT: 100000000
      networks:
        gitsearch_network:
          ipv4_address: 172.32.0.98
      depends_on:
        - db


networks:
  gitsearch_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
