---
services:
    gitsearch:
        image: gitsearch
        container_name: gitsearch
        restart: always
        volumes:
            - "./app:/app"
        deploy:
          resources:
            limits:
              cpus: "1.0"
              memory: 8G
        networks:
          gitsearch_network:
            ipv4_address: 172.32.0.99

    db:
      image: mariadb:10.3
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: changeme
      ports:
        - "3306:3306"
      networks:
        gitsearch_network:
          ipv4_address: 172.32.0.97

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_ARBITRARY: "1"
        PMA_HOST: "172.32.0.97"
        PMA_PORT: "3306"
      networks:
        gitsearch_network:
          ipv4_address: 172.32.0.98


networks:
  gitsearch_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16